version: '3.8'

services:
  redis:
    image: "redis:7.2.1-alpine"
    volumes:
      - redis-data:/data
    networks:
      - backend
    ports:
      - "6379:6379"
    expose:
      - "6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    networks:
      - backend
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
  crypto-recommendation:
    image: "crypto-recommendation:latest"
    links:
      - redis:redis
    networks:
      - backend
    environment:
      - "SPRING_PROFILES_ACTIVE=compose"
    ports:
      - "8080:8080"
networks:
  backend:
    driver:
      bridge
volumes:
  redis-data: